DROP TABLE IF EXISTS ARCHIVISTA CASCADE;
DROP TABLE IF EXISTS RESPONSABILE_EVENTI CASCADE;
DROP TABLE IF EXISTS TECNICO CASCADE;
DROP TABLE IF EXISTS RESTAURATORE CASCADE;
DROP TABLE IF EXISTS CERTIFICATO CASCADE;
DROP TABLE IF EXISTS TEAM CASCADE;
DROP TABLE IF EXISTS EVENTO CASCADE;
DROP TABLE IF EXISTS SEDE CASCADE;
DROP TABLE IF EXISTS SALA CASCADE;
DROP TABLE IF EXISTS PROIEZIONE CASCADE;
DROP TABLE IF EXISTS MOSTRA CASCADE;
DROP TABLE IF EXISTS RASSEGNA CASCADE;
DROP TABLE IF EXISTS INCONTRO_CAST CASCADE;
DROP TABLE IF EXISTS INVITO CASCADE;
DROP TABLE IF EXISTS PROGRAMMAZIONE_FILM CASCADE;
DROP TABLE IF EXISTS FILM CASCADE;
DROP TABLE IF EXISTS REGIA CASCADE;
DROP TABLE IF EXISTS RECITAZIONE CASCADE;
DROP TABLE IF EXISTS REGISTA CASCADE;
DROP TABLE IF EXISTS ATTORE CASCADE;
DROP TABLE IF EXISTS BENE_CULTURALE CASCADE;
DROP TABLE IF EXISTS MATERIALE_DIGITALE CASCADE;
DROP TABLE IF EXISTS ARCHIVIO CASCADE;
DROP TABLE IF EXISTS MATERIALE_FISICO CASCADE;
DROP TABLE IF EXISTS VERIFICA CASCADE;
DROP TABLE IF EXISTS RESTAURO CASCADE;
DROP TABLE IF EXISTS PELLICOLA CASCADE;
DROP TABLE IF EXISTS MANIFESTO CASCADE;
DROP TABLE IF EXISTS COLLEZIONE CASCADE;
DROP TABLE IF EXISTS UTENTE_PUBBLICO CASCADE;
DROP TABLE IF EXISTS BIGLIETTO CASCADE;
DROP TABLE IF EXISTS ENTE CASCADE;
DROP TABLE IF EXISTS RICHIESTA_PRESTITO CASCADE;
DROP TABLE IF EXISTS PRESTITO_CULTURALE CASCADE;    
DROP TABLE IF EXISTS MAGAZZINO CASCADE;
DROP TABLE IF EXISTS SEZIONE CASCADE;   
DROP TABLE IF EXISTS FOTOGRAFIA_ANALOGICA CASCADE;   

--drop dei domini 
DROP DOMAIN IF EXISTS TIPO_MATERIALE CASCADE;
DROP DOMAIN IF EXISTS STATO_RICHIESTA CASCADE;
DROP DOMAIN IF EXISTS STATO_PRESTITO CASCADE;
DROP DOMAIN IF EXISTS STATO_CONSERVAZIONE CASCADE;
DROP DOMAIN IF EXISTS NOME_SEDE CASCADE;
DROP DOMAIN IF EXISTS CATEGORIA_FILM CASCADE;
DROP DOMAIN IF EXISTS GENERE_FILM CASCADE;
DROP DOMAIN IF EXISTS MILLIMETRI CASCADE;
DROP DOMAIN IF EXISTS ACCESSO CASCADE;
DROP DOMAIN IF EXISTS TIPO_MATERIALE_FISICO CASCADE;
DROP DOMAIN IF EXISTS TIPOLOGIA_COLLEZIONE CASCADE;
DROP DOMAIN IF EXISTS TIPO_SUPPORTO_FOTO CASCADE;
DROP DOMAIN IF EXISTS FORMATO_RICHIESTO CASCADE;
------------------------------------------------------------




--Creazione dei domini
CREATE DOMAIN TIPO_MATERIALE AS VARCHAR(30)
CHECK (VALUE IN('fotoDigitale', 'filmDigitale')); 

CREATE DOMAIN STATO_RICHIESTA AS VARCHAR(30)
CHECK (VALUE IN('inElaborazione', 'accettata', 'rifiutata')); 

CREATE DOMAIN STATO_PRESTITO AS VARCHAR(30)
CHECK (VALUE IN('attivo', 'scaduto', 'restituito'));

CREATE DOMAIN STATO_CONSERVAZIONE AS VARCHAR(30)
CHECK (VALUE IN('eccellente', 'buono', 'soddisfacente', 'critico')); 

CREATE DOMAIN NOME_SEDE AS VARCHAR(30)
CHECK (VALUE IN('Palazzo delle Esposizioni', 'Casa del Cinema'));

CREATE DOMAIN CATEGORIA_FILM AS VARCHAR(50)
CHECK(VALUE IN('lungometraggio', 'cortometraggio', 'documentario'));

CREATE DOMAIN GENERE_FILM AS VARCHAR(50)
CHECK(VALUE IN('Azione', 'Fantascienza', 'Romantico', 'Commedia', 'Drammatico', 'Animazione', 'Thriller', 'Horror', 'Storico'));

CREATE DOMAIN MILLIMETRI AS VARCHAR(10)
CHECK(VALUE IN('35mm', '16mm', '70mm', '28mm', '9.5mm', '8mm', 'super8'));

CREATE DOMAIN ACCESSO AS VARCHAR(10)
CHECK(VALUE IN('pubblico', 'riservato'));

CREATE DOMAIN TIPO_MATERIALE_FISICO AS VARCHAR(30)
CHECK(VALUE IN('pellicola', 'manifesto', 'collezioneFotografica'));

CREATE DOMAIN TIPOLOGIA_COLLEZIONE AS VARCHAR(30)
CHECK(VALUE IN('ritratti', 'fotoScena', 'fotoBackstage'));

CREATE DOMAIN TIPO_SUPPORTO_FOTO AS VARCHAR(30)
CHECK(VALUE IN('pellicola negativa', 'lastra', 'stampa', 'diapositiva'));

CREATE DOMAIN FORMATO_RICHIESTO AS VARCHAR(30)
CHECK(VALUE IN('filmDigitale', 'pellicola'));

--creazione delle tabelle
CREATE TABLE ARCHIVISTA(
    Matricola SERIAL PRIMARY KEY,
    Nome VARCHAR(50),
    Cognome VARCHAR(50),
    Email VARCHAR(100) UNIQUE
);

CREATE TABLE RESTAURATORE(
    Matricola SERIAL PRIMARY KEY,
    Nome VARCHAR(50),
    Cognome VARCHAR(50),
    Email VARCHAR(100) UNIQUE
);
CREATE TABLE CERTIFICATO(
    IdCertificato SERIAL PRIMARY KEY,
    DataRilascio DATE,
    Specializzazione VARCHAR(100),
    Restauratore INT NOT NULL,
    FOREIGN KEY(Restauratore) REFERENCES RESTAURATORE(Matricola)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE RESPONSABILE_EVENTI(
    Matricola SERIAL PRIMARY KEY,
    Nome VARCHAR(50),
    Cognome VARCHAR(50),
    Email VARCHAR(100) UNIQUE
);

CREATE TABLE TEAM(
    IdTeam SERIAL PRIMARY KEY,
    Nome VARCHAR(50)
);

CREATE TABLE SEDE(
    IdSede SERIAL PRIMARY KEY,
    NomeSede NOME_SEDE,
    Via VARCHAR(50),
    NrCivico VARCHAR(4),
    Cap CHAR(5),
    Provincia VARCHAR(50),
    Citta VARCHAR(50),

);

CREATE TABLE TECNICO(
    Matricola SERIAL PRIMARY KEY,
    Nome VARCHAR(50),
    Cognome VARCHAR(50),
    Email VARCHAR(100) UNIQUE,
    Team INT,
    FOREIGN KEY(Team) REFERENCES TEAM(IdTeam)
        ON DELETE SET NULL
);

CREATE TABLE FILM(
    IdFilm SERIAL PRIMARY KEY,
    Titolo VARCHAR(100) NOT NULL,
    AnnoProduzione INT CHECK (AnnoProduzione > 1895),
    Durata INT CHECK(Durata>0),
    Categoria CATEGORIA_FILM,
    Paese VARCHAR(50),
    Genere GENERE_FILM,
    LinguaOriginale VARCHAR(30)
);

CREATE TABLE REGISTA(
    IdRegista SERIAL PRIMARY KEY,
    CodiceFiscale CHAR(16) UNIQUE,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL,
    Nazionalita VARCHAR(50) NOT NULL,
    DataDiNascita DATE NOT NULL
);
CREATE TABLE ATTORE(
    IdAttore SERIAL PRIMARY KEY,
    CodiceFiscale CHAR(16) UNIQUE,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL,
    DataDiNascita DATE NOT NULL
);

CREATE TABLE EVENTO(
    IdEvento SERIAL PRIMARY KEY,
    Titolo VARCHAR(100),
    DataInizio DATE DEFAULT CURRENT_DATE,
    DataFine DATE DEFAULT CURRENT_DATE CHECK (DataFine >= DataInizio),
    OrarioInizio TIME DEFAULT CURRENT_TIME,
    OrarioFine TIME DEFAULT CURRENT_TIME,
    Accesso ACCESSO,
    Sede INT NOT NULL,
    FOREIGN KEY(Sede) REFERENCES SEDE(IdSede)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE SALA(
    NumeroSala INT,
    IdSede INT,
    NomeSede NOME_SEDE CHECK (NomeSede ='Casa del Cinema'),
    NrPostiFila INT NOT NULL CHECK(NrPostiFila > 0),
    NrFile INT NOT NULL CHECK(NrFile > 0),
    PRIMARY KEY(NumeroSala, IdSede),
    FOREIGN KEY (IdSede, NomeSede) REFERENCES SEDE(IdSede, NomeSede)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE MOSTRA(
    IdEvento INT PRIMARY KEY,
    Nome VARCHAR(50),
    Descrizione TEXT,
    FOREIGN KEY (IdEvento) REFERENCES EVENTO(IdEvento)
    ON DELETE SET NULL
);
CREATE TABLE RASSEGNA(
    IdEvento INT PRIMARY KEY,
    Nome VARCHAR(50),
    Descrizione TEXT,
    FOREIGN KEY (IdEvento) REFERENCES EVENTO(IdEvento)
    ON DELETE SET NULL
);
CREATE TABLE INCONTRO_CAST(
    IdEvento INT PRIMARY KEY,
    Nome VARCHAR(50),
    Descrizione TEXT,
    FOREIGN KEY (IdEvento) REFERENCES EVENTO(IdEvento)
    ON DELETE SET NULL
);

CREATE TABLE INVITO(
    IdInvito SERIAL PRIMARY KEY,
    Incontro INT,
    Regista INT,
    Attore INT,
    CONSTRAINT check_invitati CHECK (
        (Attore IS NOT NULL AND Regista IS NULL) OR
        (Attore IS NULL AND Regista IS NOT NULL) 
    ),
    FOREIGN KEY (Incontro) REFERENCES INCONTRO_CAST(IdEvento)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Regista) REFERENCES REGISTA(IdRegista)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Attore) REFERENCES ATTORE(IdAttore)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE PROGRAMMAZIONE_FILM(
    IdProgrammazione SERIAL PRIMARY KEY,
    Evento INT,
    Film INT,
    FOREIGN KEY (Evento) REFERENCES EVENTO(IdEvento)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Film) REFERENCES FILM(IdFilm)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


CREATE TABLE REGIA(
    IdRegia SERIAL PRIMARY KEY,
    Film INT,
    Regista INT,
    FOREIGN KEY (Film) REFERENCES FILM(IdFilm)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Regista) REFERENCES REGISTA(IdRegista)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE RECITAZIONE(
    IdRecitazione SERIAL PRIMARY KEY,
    Film INT,
    Attore INT,
    FOREIGN KEY (Film) REFERENCES FILM(IdFilm)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Attore) REFERENCES ATTORE(IdAttore)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE BENE_CULTURALE(
    IdBeneCulturale SERIAL PRIMARY KEY,
    Film INT,
    DisponibilitaPrestito BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (Film) REFERENCES FILM(IdFilm)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE PROIEZIONE(
    IdEvento INT PRIMARY KEY,
    Nome VARCHAR(100),
    Descrizione TEXT,
    DisponibilitaBiglietti INT, --Vincolo 3, deve essere uguale alla capienza della sala nel momento in cui viene inizializzato
    TecnicoAssistente INT,
    BeneCulturale INT,
    NoteOperative VARCHAR(100),
    ProblemiTecnici TEXT,
    NumeroSala INT NOT NULL,
    IdSede INT NOT NULL,
    FOREIGN KEY (TecnicoAssistente) REFERENCES TECNICO(Matricola)
    ON DELETE SET NULL,
    FOREIGN KEY (BeneCulturale) REFERENCES BENE_CULTURALE(IdBeneCulturale)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (NumeroSala, IdSede) REFERENCES SALA(NumeroSala, IdSede)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (IdEvento) REFERENCES EVENTO(IdEvento) ON DELETE SET NULL
);
CREATE TABLE ARCHIVIO(
    IdArchivio SERIAL PRIMARY KEY,
    Localizzazione TEXT,
    LivelloAccesso TEXT,
    Backup TEXT,
    Tipo TEXT
);

CREATE TABLE MATERIALE_DIGITALE(
    IdBene INT NOT NULL,
    Nome VARCHAR(100),
    TipoMateriale TIPO_MATERIALE,
    Estensione VARCHAR(5),
    Risoluzione VARCHAR(30),
    PathFile TEXT,
    Dimensione TEXT,
    DataDigitalizzazione DATE,
    Archivio INT,
    UNIQUE(Nome, Archivio),
    FOREIGN KEY (IdBene) REFERENCES BENE_CULTURALE(IdBeneCulturale)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (Archivio) REFERENCES ARCHIVIO(IdArchivio)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE MAGAZZINO(
    IdMagazzino SERIAL PRIMARY KEY,
    Nome VARCHAR(50),
    Tipologia VARCHAR(30)
);

CREATE TABLE SEZIONE(
    NumeroSezione SERIAL NOT NULL,
    Magazzino INT NOT NULL,
    TipoMateriale TIPO_MATERIALE_FISICO,
	TemperaturaMedia INT,
    UmiditaMedia INT,
    UNIQUE(NumeroSezione, Magazzino),
    FOREIGN KEY(Magazzino) REFERENCES MAGAZZINO(IdMagazzino)
    ON DELETE CASCADE
);

CREATE TABLE MATERIALE_FISICO(
    IdBene INT NOT NULL PRIMARY KEY,
    StatoConservazione STATO_CONSERVAZIONE,
    Collocazione INT NOT NULL,
    FOREIGN KEY(IdBene) REFERENCES BENE_CULTURALE(IdBeneCulturale)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY(Collocazione) REFERENCES MAGAZZINO(IdMagazzino)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE PELLICOLA(
    IdBene INT NOT NULL PRIMARY KEY,
    Millimetri MILLIMETRI,
    FOREIGN KEY(IdBene) REFERENCES MATERIALE_FISICO(IdBene)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE MANIFESTO(
    IdBene INT NOT NULL PRIMARY KEY,
    Paese VARCHAR(50),
    Lingua VARCHAR(50),
    Formato VARCHAR(50), 
    Autore VARCHAR(100), 
    Provenienza VARCHAR(50), 
    DataAcquisizione DATE,
    Anno INT CHECK(Anno>1895),
    FOREIGN KEY(IdBene) REFERENCES MATERIALE_FISICO(IdBene)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


CREATE TABLE VERIFICA(
    IdVerifica SERIAL PRIMARY KEY,
    IdMateriale INT NOT NULL,
    DataVerifica DATE DEFAULT CURRENT_DATE,
    LivelloRiscontrato STATO_CONSERVAZIONE,
    DichiarazioneDati TEXT,
    InterventoConsigliato TEXT,
    ArchivistaResponsabile INT,
    UNIQUE(IdMateriale, DataVerifica),
    FOREIGN KEY(IdMateriale) REFERENCES MATERIALE_FISICO(IdBene)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY(ArchivistaResponsabile) REFERENCES ARCHIVISTA(Matricola)
    ON DELETE SET NULL
);

CREATE TABLE RESTAURO(
    IdRestauro SERIAL PRIMARY KEY,
    Materiale INT NOT NULL,
    TipoIntervento VARCHAR(50),
    DataFine DATE,
    Restauratore INT,
    Esito STATO_CONSERVAZIONE, --modifica automaticamente lo stato del materiale fisico al valore di esito
    TeamSupporto INT,
    Verifica INT,
    FOREIGN KEY(Materiale) REFERENCES MATERIALE_FISICO(IdBene)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY(Restauratore) REFERENCES RESTAURATORE(Matricola)
    ON DELETE SET NULL,
    FOREIGN KEY(TeamSupporto) REFERENCES TEAM(IdTeam)
    ON DELETE SET NULL,
    FOREIGN KEY(Verifica) REFERENCES VERIFICA(IdVerifica)
    ON DELETE SET NULL
);

CREATE TABLE COLLEZIONE(
    IdBene INT NOT NULL PRIMARY KEY,
    Titolo VARCHAR(100),
    Tipologia TIPOLOGIA_COLLEZIONE,
    Descrizione TEXT,
    Autore VARCHAR(100),
    Provenienza VARCHAR(50),
    DataAquisizione DATE DEFAULT CURRENT_DATE,
    Anno INT CHECK (Anno>1895),
    FOREIGN KEY(IdBene) REFERENCES MATERIALE_FISICO(IdBene)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


CREATE TABLE FOTOGRAFIA_ANALOGICA(
    IdFotografia SERIAL PRIMARY KEY,
    Fotografo VARCHAR(100),
    DataScatto DATE,
    TipoSupporto TIPO_SUPPORTO_FOTO,
    Collezione INT NOT NULL,
    FOREIGN KEY(Collezione) REFERENCES COLLEZIONE(IdBene)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE UTENTE_PUBBLICO(
    IdUtente SERIAL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL,
    CodiceFiscale CHAR(16) UNIQUE NOT NULL,
    Email VARCHAR(50) UNIQUE
);
CREATE TABLE BIGLIETTO(
    IdBiglietto SERIAL PRIMARY KEY,
    Proiezione INT NOT NULL,
    Cliente INT NOT NULL,
    DataAcquisto TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NumeroPosto INT NOT NULL,
    Fila INT NOT NULL,
    Prezzo DECIMAL(8,2),
    UNIQUE(Proiezione, Fila, NumeroPosto),
    FOREIGN KEY(Proiezione) REFERENCES PROIEZIONE(IdEvento)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY(Cliente) REFERENCES UTENTE_PUBBLICO(IdUtente)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE ENTE(
    CredenzialiUtente INT NOT NULL,
    Denominazione VARCHAR(70),
    Email VARCHAR(50) UNIQUE,
    Telefono VARCHAR(10),
    Via VARCHAR(50),
    NrCivico VARCHAR(4),
    Cap CHAR(5),
    Provincia VARCHAR(50),
    Citta VARCHAR(50),
    Piva CHAR(11),
    Tipologia VARCHAR(50),
    CodiceFiscaleRappresentante CHAR(16) UNIQUE NOT NULL,
    NomeRappresentante VARCHAR(30) NOT NULL,
    CognomeRappresentante VARCHAR(30) NOT NULL,
    TelefonoRappresentante VARCHAR(10),
    FOREIGN KEY(CredenzialiUtente) REFERENCES UTENTE_PUBBLICO(IdUtente)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
CREATE TABLE RICHIESTA_PRESTITO(
    IdRichiesta SERIAL PRIMARY KEY,
    Richiedente INT NOT NULL,
    BeneCulturale INT NOT NULL,
    ArchivistaResponsabile INT,
    DataInvio DATE DEFAULT CURRENT_DATE,
    Documentazione TEXT,
    StatoRichiesta STATO_RICHIESTA DEFAULT 'inElaborazione',
    MotivazioneRifiuto VARCHAR(100),
    FormatoRichiesto FORMATO_RICHIESTO,
    DataPrevistaProiezione DATE CHECK(DataPrevistaProiezione > DataInvio),
    Luogo VARCHAR(50),
    FOREIGN KEY(Richiedente) REFERENCES UTENTE_PUBBLICO(IdUtente)
    ON DELETE SET NULL,
    FOREIGN KEY(BeneCulturale) REFERENCES BENE_CULTURALE(IdBeneCulturale)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY(ArchivistaResponsabile) REFERENCES ARCHIVISTA(Matricola)
    ON DELETE SET NULL

);
CREATE TABLE PRESTITO_CULTURALE(
    Richiesta INT NOT NULL PRIMARY KEY,
    Quota DECIMAL(8,2),
    DataInizio DATE DEFAULT CURRENT_DATE,
    DataFine DATE DEFAULT CURRENT_DATE + INTERVAL '1 month',
    StatoPrestito STATO_PRESTITO,
    RestituzioneEffettiva DATE,
    Note TEXT,
    FOREIGN KEY(Richiesta) REFERENCES RICHIESTA_PRESTITO(IdRichiesta)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);









